In [2]:
# 🚀 Motor Predictor - Lanzador desde notebooks
import os, sys
from IPython import get_ipython

BASE_DIR = r"C:/Users/delpi/OneDrive/Tesis/ADRpy-VTOL/ADRpy"
ANALISIS_DIR = os.path.join(BASE_DIR, "analisis")
if ANALISIS_DIR not in sys.path:
    sys.path.insert(0, ANALISIS_DIR)

# Preferimos el Excel de Data si está disponible; sino, intentamos un fallback en Results
ruta_preferida = os.path.join(ANALISIS_DIR, "Data", "Datos_aeronaves.xlsx")
ruta_fallback = os.path.join(ANALISIS_DIR, "Results", "Datos_imputados.xlsx")


def _is_readable(path: str) -> bool:
    try:
        with open(path, "rb"):
            return True
    except Exception as e:
        print(f"ℹ️ No se pudo abrir en modo lectura {path!r}: {e}")
        return False

ruta_archivo = None
if _is_readable(ruta_preferida):
    ruta_archivo = ruta_preferida
elif _is_readable(ruta_fallback):
    ruta_archivo = ruta_fallback

script_path = os.path.join(ANALISIS_DIR, "main.py")
args = ""
if ruta_archivo:
    args = f' -- --ruta-archivo "{ruta_archivo}"'

print(f"▶ Ejecutando: {script_path}{' con ruta-archivo' if ruta_archivo else ''}")
try:
    get_ipython().run_line_magic("run", f'-i "{script_path}"{args}')
except SystemExit as e:
    print(f"⛔ El script solicitó terminar con código {e.code}.")
except Exception as e:
    print(f"❌ Error al ejecutar main.py: {e}")

DEBUG: ruta_archivo antes de validar: 'C:\Users\delpi\OneDrive\Tesis\ADRpy-VTOL\ADRpy\analisis\Data\Datos_aeronaves.xlsx'
=== Cargando datos desde el archivo: C:\Users\delpi\OneDrive\Tesis\ADRpy-VTOL\ADRpy\analisis\Data\Datos_aeronaves.xlsx ===

=== Resumen inicial del DataFrame cargado ===
<class 'pandas.core.frame.DataFrame'>
Index: 83 entries, Stalker XE to Omnibe (BETA UAS)
Data columns (total 48 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Distancia de carrera requerida para despegue        83 non-null     object
 1   Altitud a la que se realiza el crucero              83 non-null     object
 2   Velocidad a la que se realiza el crucero (m/s TAS)  83 non-null     object
 3   Techo de servicio máximo                            83 non-null     object
 4   Velocidad de pérdida limpia (m/s CAS)               83 non-null     object
 5   Área del ala                                        83 non-null     object
 6   Relación de aspecto del ala                         83 non-null     object
 7   Longitud del fuselaje                               83 non-null     object
 8   Profundidad del fuselaje                            83 non-null     object
 9   Ancho del fuselaje                                  83 non-null     object
 10  Peso máximo al despegue (MTOW)                      83 non-null     float64
 11  Alcance de la aeronave (km)                         82 non-null     object
 12  Autonomía de la aeronave (h)                        83 non-null     object
 13  Velocidad máxima (m/s IAS)                          83 non-null     object
 14  Velocidad de pérdida (m/s CAS)                      83 non-null     object
 15  Tasa de ascenso                                     83 non-null     object
 16  Radio de giro                                       83 non-null     object
 17  Envergadura                                         83 non-null     object
 18  Cuerda                                              83 non-null     object
 19  Payload                                             83 non-null     object
 20  duracion en VTOL                                    83 non-null     object
 21  Velocidad crucero (m/s IAS)                         83 non-null     object
 22  Battery Weight                                      83 non-null     object
 23  Peso frame                                          83 non-null     object
 24  Peso vacio - fuel y battery                         83 non-null     object
 25  Peso Vacio (MTOW - payload)                         83 non-null     object
 26  Maximum Crosswind (rachas)                          83 non-null     object
 27  Maximum Crosswind (sostenido)                       83 non-null     object
 28  Rango de comunicación                               83 non-null     object
 29  Wing Loading                                        83 non-null     object
 30  Potencia específica (P/W)                           83 non-null     object
 31  Capacidad combustible                               83 non-null     object
 32  Consumo                                             83 non-null     object
 33  Potencia Watts                                      83 non-null     object
 34  Potencia HP                                         83 non-null     object
 35  Precio                                              83 non-null     object
 36  Tiempo de emergencia en vuelo                       83 non-null     object
 37  Despegue                                            83 non-null     int64
 38  Propulsión horizontal                               83 non-null     int64
 39  Propulsión vertical                                 83 non-null     int64
 40  Cantidad de motores propulsión vertical             83 non-null     int64
 41  Cantidad de motores propulsión horizontal           83 non-null     int64
 42  Misión                                              83 non-null     int64
 43  Clase                                               83 non-null     int64
 44  Unnamed: 45                                         0 non-null      float64
 45  Unnamed: 46                                         0 non-null      float64
 46  Unnamed: 47                                         0 non-null      float64
 47  Unnamed: 48                                         7 non-null      object
dtypes: float64(4), int64(7), object(37)
memory usage: 31.8+ KB
None
✅ Data loaded successfully from: C:\Users\delpi\OneDrive\Tesis\ADRpy-VTOL\ADRpy\analisis\Data\Datos_aeronaves.xlsx

🔎 === Validating loaded data ===

➡️ === Proceeding with data processing ===

📋 Initial headers loaded:
['Distancia de carrera requerida para despegue', 'Altitud a la que se realiza el crucero', 'Velocidad a la que se realiza el crucero (m/s TAS)', 'Techo de servicio máximo', 'Velocidad de pérdida limpia (m/s CAS)', 'Área del ala', 'Relación de aspecto del ala', 'Longitud del fuselaje', 'Profundidad del fuselaje', 'Ancho del fuselaje', 'Peso máximo al despegue (MTOW)', 'Alcance de la aeronave (km)', 'Autonomía de la aeronave (h)', 'Velocidad máxima (m/s IAS)', 'Velocidad de pérdida (m/s CAS)', 'Tasa de ascenso', 'Radio de giro', 'Envergadura', 'Cuerda', 'Payload', 'duracion en VTOL', 'Velocidad crucero (m/s IAS)', 'Battery Weight', 'Peso frame', 'Peso vacio - fuel y battery', 'Peso Vacio (MTOW - payload)', 'Maximum Crosswind (rachas)', 'Maximum Crosswind (sostenido)', 'Rango de comunicación', 'Wing Loading', 'Potencia específica (P/W)', 'Capacidad combustible', 'Consumo', 'Potencia Watts', 'Potencia HP', 'Precio', 'Tiempo de emergencia en vuelo', 'Despegue', 'Propulsión horizontal', 'Propulsión vertical', 'Cantidad de motores propulsión vertical', 'Cantidad de motores propulsión horizontal', 'Misión', 'Clase', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48']

🌐 === Displaying initial data in HTML format ===

⚙️ === Processing data ===
=== Inicio del procesamiento de datos ===

=== Comprobación de duplicados ===
No se encontraron duplicados en índices o columnas.

=== Convirtiendo valores a numéricos donde sea posible ===
=== Procesamiento completado ===

🧮 === Completing derived fields for data enrichment ===

❌ Headers were modified during processing.

🌐 === Displaying processed data in HTML format ===

🔎 Parameters available in df_procesado before selection:
['Distancia de carrera requerida para despegue', 'Altitud a la que se realiza el crucero', 'Velocidad a la que se realiza el crucero (m/s TAS)', 'Techo de servicio máximo', 'Velocidad de pérdida limpia (m/s CAS)', 'Área del ala', 'Relación de aspecto del ala', 'Longitud del fuselaje', 'Profundidad del fuselaje', 'Ancho del fuselaje', 'Peso máximo al despegue (MTOW)', 'Alcance de la aeronave (km)', 'Autonomía de la aeronave (h)', 'Velocidad máxima (m/s IAS)', 'Velocidad de pérdida (m/s CAS)', 'Tasa de ascenso', 'Radio de giro', 'Envergadura', 'Cuerda', 'Payload', 'duracion en VTOL', 'Velocidad crucero (m/s IAS)', 'Battery Weight', 'Peso frame', 'Peso vacio - fuel y battery', 'Peso Vacio (MTOW - payload)', 'Maximum Crosswind (rachas)', 'Maximum Crosswind (sostenido)', 'Rango de comunicación', 'Wing Loading', 'Potencia específica (P/W)', 'Capacidad combustible', 'Consumo', 'Potencia Watts', 'Potencia HP', 'Precio', 'Tiempo de emergencia en vuelo', 'Despegue', 'Propulsión horizontal', 'Propulsión vertical', 'Cantidad de motores propulsión vertical', 'Cantidad de motores propulsión horizontal', 'Misión', 'Clase', 'Unnamed: 48', 'Alcance de la aeronave', 'Altitud de crucero']

=== Selección de Parámetros ===
Parámetros disponibles:
1. Distancia de carrera requerida para despegue
2. Altitud a la que se realiza el crucero
3. Velocidad a la que se realiza el crucero (m/s TAS)
4. Techo de servicio máximo
5. Velocidad de pérdida limpia (m/s CAS)
6. Área del ala
7. Relación de aspecto del ala
8. Longitud del fuselaje
9. Profundidad del fuselaje
10. Ancho del fuselaje
11. Peso máximo al despegue (MTOW)
12. Alcance de la aeronave (km)
13. Autonomía de la aeronave (h)
14. Velocidad máxima (m/s IAS)
15. Velocidad de pérdida (m/s CAS)
16. Tasa de ascenso
17. Radio de giro
18. Envergadura
19. Cuerda
20. Payload
21. duracion en VTOL
22. Velocidad crucero (m/s IAS)
23. Battery Weight
24. Peso frame
25. Peso vacio - fuel y battery
26. Peso Vacio (MTOW - payload)
27. Maximum Crosswind (rachas)
28. Maximum Crosswind (sostenido)
29. Rango de comunicación
30. Wing Loading
31. Potencia específica (P/W)
32. Capacidad combustible
33. Consumo
34. Potencia Watts
35. Potencia HP
36. Precio
37. Tiempo de emergencia en vuelo
38. Despegue
39. Propulsión horizontal
40. Propulsión vertical
41. Cantidad de motores propulsión vertical
42. Cantidad de motores propulsión horizontal
43. Misión
44. Clase
45. Unnamed: 48
46. Alcance de la aeronave
47. Altitud de crucero

Preseleccionados:  3, 4, 6, 7, 8, 11, 46, 14, 15, 18, 19, 20, 10, 35, 34, 29, 43, 38
Parámetros seleccionados después de filtrar:
['Velocidad a la que se realiza el crucero (m/s TAS)', 'Techo de servicio máximo', 'Área del ala', 'Relación de aspecto del ala', 'Longitud del fuselaje', 'Peso máximo al despegue (MTOW)', 'Alcance de la aeronave', 'Velocidad máxima (m/s IAS)', 'Velocidad de pérdida (m/s CAS)', 'Envergadura', 'Cuerda', 'Payload', 'Ancho del fuselaje', 'Potencia HP', 'Potencia Watts', 'Rango de comunicación', 'Misión', 'Despegue']
🔎 Parameters selected after filtering:
['Velocidad a la que se realiza el crucero (m/s TAS)', 'Techo de servicio máximo', 'Área del ala', 'Relación de aspecto del ala', 'Longitud del fuselaje', 'Peso máximo al despegue (MTOW)', 'Alcance de la aeronave', 'Velocidad máxima (m/s IAS)', 'Velocidad de pérdida (m/s CAS)', 'Envergadura', 'Cuerda', 'Payload', 'Ancho del fuselaje', 'Potencia HP', 'Potencia Watts', 'Rango de comunicación', 'Misión', 'Despegue']

=== Filas con datos faltantes ===
1. Stalker XE
2. Stalker VXE30 Fuel Cell
3. Stalker VXE30 Battery
4. Edge Autonomy Penguin C Mk 2.5 VTOL
5. Aerosonde Mk. 4.7 Fixed Wing
6. Aerosonde Mk. 4.7 VTOL
7. Aerosonde Mk. 4.8 Fixed wing
8. Aerosonde Mk. 4.8 VTOL FTUAS
9. AAI Aerosonde
10. Fulmar X
11. Orbiter 4
12. Orbiter 3
13. Mantis
14. ScanEagle
15. Integrator
16. Integrator VTOL
17. Integrator Extended Range
18. ScanEagle 3
19. RQ Nan 21A Blackjack
20. DeltaQuad Evo
21. DeltaQuad Pro #MAP
22. DeltaQuad Pro #CARGO
23. V21
24. V25
25. V32
26. V35
27. V39
28. Volitation VT370
29. Skyeye 2600
30. Skyeye 2930 VTOL
31. Skyeye 3600
32. Skyeye 3600 VTOL
33. Skyeye 5000
34. Skyeye 5000 VTOL
35. Skyeye 5000 VTOL octo
36. Volitation VT510
37. Ascend
38. Transition
39. Reach
40. HYFLY H510
41. HYFLY H405
42. JOUAV CW-007
43. JOUAV CW-15
44. JOUAV CW-25E
45. JOUAV CW-25H
46. JOUAV CW-25
47. JOUAV CW-30E
48. JOUAV CW-80E
49. L3Harris FVR–90
50. SwoopAero Kite™
51. YANGDA Sky Whale Heavy Lift Long Endurance Electric VTOL Drone
52. YANGDA Sky Whale Max Electric Heavy Lift Long Endurance VTOL Drone
53. YANGDA Sky Whale Max Hybrid Heavy Lift Long Endurance VTOL Drone
54. YANGDA Sky Whale Mini Electric Long Endurance VTOL Drone
55. DOOSAN DJ25
56. WingtraOne GEN II
57. Trinity Pro
58. Trinity F90+
59. Vector
60. T-Drones VA32
61. Avy Aera
62. Event 38 E400 VTOL
63. Aerovel Flexrotor
64. FIXAR 007 NG
65. Autel Dragonfish
66. Autel Dragonfish Pro
67. Atmos Marlyn Cobalt (VTOL ala fija)
68. Aliaca VTOL UAS EVO
69. Aliaca VTOL UAS ER
70. Aliaca UAS EVO
71. Aliaca UAS ER
72. Shield AI V-BAT 128
73. AeroVironment JUMP 20
74. AeroVironment JUMP 20-X
75. T-20
76. P550
77. Puma LE
78. Puma 3 AE
79. Raven B (RQ-11B)
80. Minibe (BETA UAS / PT Pindad)
81. Raybe (BETA UAS)
82. Ruppel (BETA UAS)
83. Omnibe (BETA UAS)
🔁 Entrada inválida o vacía. Seleccionando la primera fila por defecto.

=== Analizando celdas faltantes en la fila: 'Stalker XE' ===

📊 === Generating summary of missing values by column ===

================================================================================
=== INICIO DE ITERACIÓN 1 ===
================================================================================

=== Iteración 1: Resumen antes de imputaciones ===

--------------------------------------------------------------------------------
*** IMPUTACIÓN POR SIMILITUD NUEVA - ITERACIÓN 1 ***
--------------------------------------------------------------------------------

🔄 Iniciando imputación global para 18 parámetros

=== Nueva Imputación por Similitud: Stalker XE - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Stalker XE
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Stalker VXE30 Fuel Cell - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Stalker VXE30 Fuel Cell
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Stalker VXE30 Battery - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Stalker VXE30 Battery
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Edge Autonomy Penguin C Mk 2.5 VTOL - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Edge Autonomy Penguin C Mk 2.5 VTOL
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aerosonde Mk. 4.7 Fixed Wing - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aerosonde Mk. 4.7 Fixed Wing
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aerosonde Mk. 4.7 VTOL - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aerosonde Mk. 4.7 VTOL
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aerosonde Mk. 4.8 Fixed wing - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aerosonde Mk. 4.8 Fixed wing
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aerosonde Mk. 4.8 VTOL FTUAS - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aerosonde Mk. 4.8 VTOL FTUAS
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: AAI Aerosonde - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: AAI Aerosonde
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Fulmar X - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Fulmar X
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Orbiter 4 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Orbiter 4
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Orbiter 3 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Orbiter 3
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Mantis - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Mantis
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: ScanEagle - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: ScanEagle
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Integrator - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Integrator
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Integrator VTOL - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Integrator VTOL
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Integrator Extended Range - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Integrator Extended Range
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: ScanEagle 3 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: ScanEagle 3
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: RQ Nan 21A Blackjack - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: RQ Nan 21A Blackjack
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: DeltaQuad Evo - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: DeltaQuad Evo
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: DeltaQuad Pro #MAP - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: DeltaQuad Pro #MAP
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: DeltaQuad Pro #CARGO - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: DeltaQuad Pro #CARGO
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: V21 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: V21
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: V25 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: V25
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: V32 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: V32
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: V35 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: V35
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: V39 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: V39
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Volitation VT370 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Volitation VT370
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Skyeye 2600 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Skyeye 2600
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Skyeye 2930 VTOL - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Skyeye 2930 VTOL
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Skyeye 3600 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Skyeye 3600
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Skyeye 3600 VTOL - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Skyeye 3600 VTOL
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Skyeye 5000 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Skyeye 5000
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Skyeye 5000 VTOL - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Skyeye 5000 VTOL
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Skyeye 5000 VTOL octo - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Skyeye 5000 VTOL octo
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Volitation VT510 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Volitation VT510
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Ascend - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Ascend
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Transition - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Transition
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Reach - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Reach
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: HYFLY H510 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: HYFLY H510
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: HYFLY H405 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: HYFLY H405
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: JOUAV CW-007 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: JOUAV CW-007
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: JOUAV CW-15 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: JOUAV CW-15
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: JOUAV CW-25E - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: JOUAV CW-25E
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: JOUAV CW-25H - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: JOUAV CW-25H
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: JOUAV CW-25 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: JOUAV CW-25
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: JOUAV CW-30E - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: JOUAV CW-30E
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: JOUAV CW-80E - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: JOUAV CW-80E
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: L3Harris FVR–90 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: L3Harris FVR–90
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: SwoopAero Kite™ - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: SwoopAero Kite™
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: YANGDA Sky Whale Heavy Lift Long Endurance Electric VTOL Drone - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: YANGDA Sky Whale Heavy Lift Long Endurance Electric VTOL Drone
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: YANGDA Sky Whale Max Electric Heavy Lift Long Endurance VTOL Drone - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: YANGDA Sky Whale Max Electric Heavy Lift Long Endurance VTOL Drone
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: YANGDA Sky Whale Max Hybrid Heavy Lift Long Endurance VTOL Drone - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: YANGDA Sky Whale Max Hybrid Heavy Lift Long Endurance VTOL Drone
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: YANGDA Sky Whale Mini Electric Long Endurance VTOL Drone - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: YANGDA Sky Whale Mini Electric Long Endurance VTOL Drone
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: DOOSAN DJ25 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: DOOSAN DJ25
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: WingtraOne GEN II - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: WingtraOne GEN II
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Trinity Pro - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Trinity Pro
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Trinity F90+ - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Trinity F90+
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Vector - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Vector
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: T-Drones VA32 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: T-Drones VA32
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Avy Aera - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Avy Aera
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Event 38 E400 VTOL - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Event 38 E400 VTOL
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aerovel Flexrotor - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aerovel Flexrotor
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: FIXAR 007 NG - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: FIXAR 007 NG
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Autel Dragonfish - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Autel Dragonfish
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Autel Dragonfish Pro - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Autel Dragonfish Pro
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Atmos Marlyn Cobalt (VTOL ala fija) - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Atmos Marlyn Cobalt (VTOL ala fija)
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aliaca VTOL UAS EVO - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aliaca VTOL UAS EVO
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aliaca VTOL UAS ER - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aliaca VTOL UAS ER
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aliaca UAS EVO - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aliaca UAS EVO
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aliaca UAS ER - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aliaca UAS ER
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Shield AI V-BAT 128 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Shield AI V-BAT 128
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: AeroVironment JUMP 20 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: AeroVironment JUMP 20
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82

================================================================================
=== FIN DE ITERACIÓN 1 ===
================================================================================

================================================================================
=== INICIO DE ITERACIÓN 2 ===
================================================================================

=== Iteración 2: Resumen antes de imputaciones ===

--------------------------------------------------------------------------------
*** IMPUTACIÓN POR SIMILITUD NUEVA - ITERACIÓN 2 ***
--------------------------------------------------------------------------------

🔄 Iniciando imputación global para 18 parámetros

=== Nueva Imputación por Similitud: Stalker XE - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Stalker XE
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Stalker VXE30 Fuel Cell - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Stalker VXE30 Fuel Cell
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Stalker VXE30 Battery - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Stalker VXE30 Battery
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Edge Autonomy Penguin C Mk 2.5 VTOL - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Edge Autonomy Penguin C Mk 2.5 VTOL
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aerosonde Mk. 4.7 Fixed Wing - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aerosonde Mk. 4.7 Fixed Wing
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aerosonde Mk. 4.7 VTOL - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aerosonde Mk. 4.7 VTOL
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aerosonde Mk. 4.8 Fixed wing - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aerosonde Mk. 4.8 Fixed wing
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aerosonde Mk. 4.8 VTOL FTUAS - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aerosonde Mk. 4.8 VTOL FTUAS
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: AAI Aerosonde - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: AAI Aerosonde
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Fulmar X - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Fulmar X
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Orbiter 4 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Orbiter 4
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Orbiter 3 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Orbiter 3
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Mantis - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Mantis
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: ScanEagle - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: ScanEagle
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Integrator - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Integrator
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Integrator VTOL - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Integrator VTOL
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Integrator Extended Range - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Integrator Extended Range
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: ScanEagle 3 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: ScanEagle 3
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: RQ Nan 21A Blackjack - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: RQ Nan 21A Blackjack
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: DeltaQuad Evo - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: DeltaQuad Evo
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: DeltaQuad Pro #MAP - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: DeltaQuad Pro #MAP
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: DeltaQuad Pro #CARGO - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: DeltaQuad Pro #CARGO
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: V21 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: V21
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: V25 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: V25
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: V32 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: V32
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: V35 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: V35
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: V39 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: V39
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Volitation VT370 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Volitation VT370
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Skyeye 2600 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Skyeye 2600
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Skyeye 2930 VTOL - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Skyeye 2930 VTOL
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Skyeye 3600 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Skyeye 3600
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Skyeye 3600 VTOL - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Skyeye 3600 VTOL
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Skyeye 5000 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Skyeye 5000
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Skyeye 5000 VTOL - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Skyeye 5000 VTOL
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Skyeye 5000 VTOL octo - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Skyeye 5000 VTOL octo
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Volitation VT510 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Volitation VT510
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Ascend - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Ascend
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Transition - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Transition
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Reach - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Reach
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: HYFLY H510 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: HYFLY H510
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: HYFLY H405 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: HYFLY H405
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: JOUAV CW-007 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: JOUAV CW-007
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: JOUAV CW-15 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: JOUAV CW-15
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: JOUAV CW-25E - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: JOUAV CW-25E
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: JOUAV CW-25H - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: JOUAV CW-25H
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: JOUAV CW-25 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: JOUAV CW-25
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: JOUAV CW-30E - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: JOUAV CW-30E
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: JOUAV CW-80E - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: JOUAV CW-80E
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: L3Harris FVR–90 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: L3Harris FVR–90
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: SwoopAero Kite™ - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: SwoopAero Kite™
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: YANGDA Sky Whale Heavy Lift Long Endurance Electric VTOL Drone - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: YANGDA Sky Whale Heavy Lift Long Endurance Electric VTOL Drone
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: YANGDA Sky Whale Max Electric Heavy Lift Long Endurance VTOL Drone - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: YANGDA Sky Whale Max Electric Heavy Lift Long Endurance VTOL Drone
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: YANGDA Sky Whale Max Hybrid Heavy Lift Long Endurance VTOL Drone - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: YANGDA Sky Whale Max Hybrid Heavy Lift Long Endurance VTOL Drone
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: YANGDA Sky Whale Mini Electric Long Endurance VTOL Drone - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: YANGDA Sky Whale Mini Electric Long Endurance VTOL Drone
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: DOOSAN DJ25 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: DOOSAN DJ25
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: WingtraOne GEN II - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: WingtraOne GEN II
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Trinity Pro - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Trinity Pro
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Trinity F90+ - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Trinity F90+
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Vector - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Vector
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: T-Drones VA32 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: T-Drones VA32
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Avy Aera - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Avy Aera
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Event 38 E400 VTOL - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Event 38 E400 VTOL
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aerovel Flexrotor - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aerovel Flexrotor
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: FIXAR 007 NG - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: FIXAR 007 NG
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Autel Dragonfish - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Autel Dragonfish
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Autel Dragonfish Pro - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Autel Dragonfish Pro
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Atmos Marlyn Cobalt (VTOL ala fija) - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Atmos Marlyn Cobalt (VTOL ala fija)
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aliaca VTOL UAS EVO - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aliaca VTOL UAS EVO
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aliaca VTOL UAS ER - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aliaca VTOL UAS ER
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aliaca UAS EVO - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aliaca UAS EVO
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aliaca UAS ER - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aliaca UAS ER
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Shield AI V-BAT 128 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Shield AI V-BAT 128
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: AeroVironment JUMP 20 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: AeroVironment JUMP 20
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82

================================================================================
=== FIN DE ITERACIÓN 2 ===
================================================================================

================================================================================
=== INICIO DE ITERACIÓN 3 ===
================================================================================

=== Iteración 3: Resumen antes de imputaciones ===

--------------------------------------------------------------------------------
*** IMPUTACIÓN POR SIMILITUD NUEVA - ITERACIÓN 3 ***
--------------------------------------------------------------------------------

🔄 Iniciando imputación global para 18 parámetros

=== Nueva Imputación por Similitud: Stalker XE - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Stalker XE
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Stalker VXE30 Fuel Cell - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Stalker VXE30 Fuel Cell
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Stalker VXE30 Battery - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Stalker VXE30 Battery
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Edge Autonomy Penguin C Mk 2.5 VTOL - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Edge Autonomy Penguin C Mk 2.5 VTOL
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aerosonde Mk. 4.7 Fixed Wing - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aerosonde Mk. 4.7 Fixed Wing
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aerosonde Mk. 4.7 VTOL - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aerosonde Mk. 4.7 VTOL
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aerosonde Mk. 4.8 Fixed wing - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aerosonde Mk. 4.8 Fixed wing
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aerosonde Mk. 4.8 VTOL FTUAS - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aerosonde Mk. 4.8 VTOL FTUAS
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: AAI Aerosonde - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: AAI Aerosonde
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Fulmar X - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Fulmar X
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Orbiter 4 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Orbiter 4
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Orbiter 3 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Orbiter 3
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Mantis - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Mantis
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: ScanEagle - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: ScanEagle
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Integrator - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Integrator
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Integrator VTOL - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Integrator VTOL
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Integrator Extended Range - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Integrator Extended Range
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: ScanEagle 3 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: ScanEagle 3
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: RQ Nan 21A Blackjack - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: RQ Nan 21A Blackjack
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: DeltaQuad Evo - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: DeltaQuad Evo
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: DeltaQuad Pro #MAP - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: DeltaQuad Pro #MAP
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: DeltaQuad Pro #CARGO - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: DeltaQuad Pro #CARGO
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: V21 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: V21
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: V25 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: V25
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: V32 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: V32
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: V35 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: V35
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: V39 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: V39
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Volitation VT370 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Volitation VT370
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Skyeye 2600 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Skyeye 2600
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Skyeye 2930 VTOL - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Skyeye 2930 VTOL
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Skyeye 3600 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Skyeye 3600
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Skyeye 3600 VTOL - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Skyeye 3600 VTOL
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Skyeye 5000 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Skyeye 5000
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Skyeye 5000 VTOL - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Skyeye 5000 VTOL
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Skyeye 5000 VTOL octo - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Skyeye 5000 VTOL octo
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Volitation VT510 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Volitation VT510
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Ascend - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Ascend
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Transition - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Transition
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Reach - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Reach
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: HYFLY H510 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: HYFLY H510
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: HYFLY H405 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: HYFLY H405
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: JOUAV CW-007 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: JOUAV CW-007
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: JOUAV CW-15 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: JOUAV CW-15
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: JOUAV CW-25E - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: JOUAV CW-25E
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: JOUAV CW-25H - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: JOUAV CW-25H
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: JOUAV CW-25 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: JOUAV CW-25
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: JOUAV CW-30E - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: JOUAV CW-30E
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: JOUAV CW-80E - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: JOUAV CW-80E
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: L3Harris FVR–90 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: L3Harris FVR–90
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: SwoopAero Kite™ - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: SwoopAero Kite™
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: YANGDA Sky Whale Heavy Lift Long Endurance Electric VTOL Drone - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: YANGDA Sky Whale Heavy Lift Long Endurance Electric VTOL Drone
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: YANGDA Sky Whale Max Electric Heavy Lift Long Endurance VTOL Drone - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: YANGDA Sky Whale Max Electric Heavy Lift Long Endurance VTOL Drone
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: YANGDA Sky Whale Max Hybrid Heavy Lift Long Endurance VTOL Drone - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: YANGDA Sky Whale Max Hybrid Heavy Lift Long Endurance VTOL Drone
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: YANGDA Sky Whale Mini Electric Long Endurance VTOL Drone - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: YANGDA Sky Whale Mini Electric Long Endurance VTOL Drone
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: DOOSAN DJ25 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: DOOSAN DJ25
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: WingtraOne GEN II - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: WingtraOne GEN II
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Trinity Pro - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Trinity Pro
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Trinity F90+ - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Trinity F90+
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Vector - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Vector
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: T-Drones VA32 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: T-Drones VA32
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Avy Aera - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Avy Aera
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Event 38 E400 VTOL - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Event 38 E400 VTOL
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aerovel Flexrotor - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aerovel Flexrotor
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: FIXAR 007 NG - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: FIXAR 007 NG
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Autel Dragonfish - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Autel Dragonfish
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Autel Dragonfish Pro - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Autel Dragonfish Pro
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Atmos Marlyn Cobalt (VTOL ala fija) - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Atmos Marlyn Cobalt (VTOL ala fija)
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aliaca VTOL UAS EVO - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aliaca VTOL UAS EVO
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aliaca VTOL UAS ER - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aliaca VTOL UAS ER
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aliaca UAS EVO - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aliaca UAS EVO
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Aliaca UAS ER - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Aliaca UAS ER
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: Shield AI V-BAT 128 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: Shield AI V-BAT 128
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82
❌ No se encontraron aeronaves similares válidas.

=== Nueva Imputación por Similitud: AeroVironment JUMP 20 - Velocidad a la que se realiza el crucero (m/s TAS) ===
🔍 Aeronave objetivo: AeroVironment JUMP 20
🔍 Parámetros disponibles en df_filtrado: 18
🔍 Aeronaves candidatas: 82

================================================================================
=== FIN DE ITERACIÓN 3 ===
================================================================================

================================================================================
=== RESUMEN FINAL ===
================================================================================
Total de iteraciones realizadas: 3
Total de valores imputados: 94
📝 [DEBUG] Archivo JSON unificado exportado a: C:\Users\delpi\OneDrive\Tesis\ADRpy-VTOL\ADRpy\analisis\Modulos\../Results\modelos_completos_por_celda.json
📊 [DEBUG] Estructura: 65 celdas con información completa

📤 === Exporting data to file: C:\Users\delpi\OneDrive\Tesis\ADRpy-VTOL\ADRpy\analisis\Results\Datos_imputados.xlsx ===
ℹ️ El archivo 'C:\Users\delpi\OneDrive\Tesis\ADRpy-VTOL\ADRpy\analisis\Results\Datos_imputados.xlsx' ya existe. Guardando como 'C:\Users\delpi\OneDrive\Tesis\ADRpy-VTOL\ADRpy\analisis\Results\Datos_imputados (1).xlsx' para evitar sobrescribir.
📤 === Exporting data to file: C:\Users\delpi\OneDrive\Tesis\ADRpy-VTOL\ADRpy\analisis\Results\Datos_imputados (1).xlsx ===
✅ Export completed. File saved as 'C:\Users\delpi\OneDrive\Tesis\ADRpy-VTOL\ADRpy\analisis\Results\Datos_imputados (1).xlsx'.

🎉 === Workflow completed. Please check the generated file. ===
✅ Script finished.